use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

use crate::paths::SDK_DOMAIN;

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/model_vendors",
        SDK_DOMAIN,
        "modelVendors.list",
    )
    .with_required_permission("intelligence.models.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/model_vendors",
        SDK_DOMAIN,
        "modelVendors.create",
    )
    .with_required_permission("intelligence.models.manage"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/models",
        SDK_DOMAIN,
        "models.list",
    )
    .with_required_permission("intelligence.models.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/models",
        SDK_DOMAIN,
        "models.create",
    )
    .with_required_permission("intelligence.models.manage"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/models/sync",
        SDK_DOMAIN,
        "models.sync",
    )
    .with_required_permission("intelligence.models.manage"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/ai/models/{modelId}",
        SDK_DOMAIN,
        "models.update",
    )
    .with_required_permission("intelligence.models.manage"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/ai/models/{modelId}",
        SDK_DOMAIN,
        "models.delete",
    )
    .with_required_permission("intelligence.models.manage"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/model_mappings",
        SDK_DOMAIN,
        "modelMappings.list",
    )
    .with_required_permission("intelligence.models.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/model_mappings",
        SDK_DOMAIN,
        "modelMappings.create",
    )
    .with_required_permission("intelligence.models.manage"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/model_mappings/resolve",
        SDK_DOMAIN,
        "modelMappings.resolve",
    )
    .with_required_permission("intelligence.models.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/ai/model_mappings/{mappingId}",
        SDK_DOMAIN,
        "modelMappings.update",
    )
    .with_required_permission("intelligence.models.manage"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/ai/model_mappings/{mappingId}",
        SDK_DOMAIN,
        "modelMappings.delete",
    )
    .with_required_permission("intelligence.models.manage"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/model_rankings",
        SDK_DOMAIN,
        "modelRankings.list",
    )
    .with_required_permission("intelligence.models.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/model_rankings/status",
        SDK_DOMAIN,
        "modelRankings.status.retrieve",
    )
    .with_required_permission("intelligence.models.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/model_rankings/jobs",
        SDK_DOMAIN,
        "modelRankings.jobs.list",
    )
    .with_required_permission("intelligence.models.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/voices",
        SDK_DOMAIN,
        "voices.list",
    )
    .with_required_permission("intelligence.models.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/models/{modelId}/voices",
        SDK_DOMAIN,
        "modelVoices.list",
    )
    .with_required_permission("intelligence.models.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/video_profiles",
        SDK_DOMAIN,
        "videoProfiles.list",
    )
    .with_required_permission("intelligence.models.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/models/{modelId}/video_profiles",
        SDK_DOMAIN,
        "modelVideoProfiles.list",
    )
    .with_required_permission("intelligence.models.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/model_rankings/refresh",
        SDK_DOMAIN,
        "modelRankings.refresh",
    )
    .with_required_permission("intelligence.models.manage"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/resources",
        SDK_DOMAIN,
        "resources.list",
    )
    .with_required_permission("intelligence.resources.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/resources",
        SDK_DOMAIN,
        "resources.create",
    )
    .with_required_permission("intelligence.resources.manage"),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/backend/v3/api/ai/resources/{resourceId}",
        SDK_DOMAIN,
        "resources.update",
    )
    .with_required_permission("intelligence.resources.manage"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/resource_groups",
        SDK_DOMAIN,
        "resourceGroups.list",
    )
    .with_required_permission("intelligence.resources.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/resource_groups",
        SDK_DOMAIN,
        "resourceGroups.create",
    )
    .with_required_permission("intelligence.resources.manage"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/resource_groups/{groupIdOrCode}/resources",
        SDK_DOMAIN,
        "resourceGroups.resources.list",
    )
    .with_required_permission("intelligence.resources.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/ai/resource_groups/{groupId}",
        SDK_DOMAIN,
        "resourceGroups.update",
    )
    .with_required_permission("intelligence.resources.manage"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/ai/resource_groups/{groupId}",
        SDK_DOMAIN,
        "resourceGroups.delete",
    )
    .with_required_permission("intelligence.resources.manage"),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
