// Generated by tools/models_sdk_generator_runner.mjs from the owner-only Models OpenAPI input.
// This file is outside generated/server-openapi so SDK ownership metadata does not pollute sdkgen output.

export const sdkMetadata = {
  name: "sdkwork-models-backend-sdk",
  packageName: "sdkwork-models-backend-sdk-generated-typescript",
  sdkOwner: "sdkwork-models",
  apiAuthority: "sdkwork-models-backend-api",
  language: "typescript",
  standardProfile: "sdkwork-v3",
  baseUrl: "http://127.0.0.1:18080",
  apiPrefix: "/backend/v3/api",
  sdkDependencies: [{"workspace":"sdkwork-appbase-backend-sdk","role":"appbase-backend-management-capability","required":true,"dependencyMode":"consumer-sdk","apiPrefix":"/backend/v3/api","apiAuthority":"sdkwork-appbase-backend-api","generatedTransportImportPolicy":"forbidden","packageByLanguage":{"typescript":"@sdkwork/appbase-backend-sdk","rust":"sdkwork-appbase-backend-sdk","java":"com.sdkwork:sdkwork-appbase-backend-sdk","python":"sdkwork-appbase-backend-sdk","go":"github.com/sdkwork/sdkwork-appbase-backend-sdk"}}],
  dependencyApiExports: [],
};

export const operations = {
  "aiResourceGroups.create": { method: "POST", path: "/backend/v3/api/ai/resource_groups" },
  "aiResourceGroups.delete": { method: "DELETE", path: "/backend/v3/api/ai/resource_groups/{groupId}" },
  "aiResourceGroups.list": { method: "GET", path: "/backend/v3/api/ai/resource_groups" },
  "aiResourceGroups.resources.list": { method: "GET", path: "/backend/v3/api/ai/resource_groups/{groupIdOrCode}/resources" },
  "aiResourceGroups.update": { method: "PATCH", path: "/backend/v3/api/ai/resource_groups/{groupId}" },
  "aiResources.create": { method: "POST", path: "/backend/v3/api/ai/resources" },
  "aiResources.list": { method: "GET", path: "/backend/v3/api/ai/resources" },
  "aiResources.update": { method: "PUT", path: "/backend/v3/api/ai/resources/{resourceId}" },
  "modelMappings.create": { method: "POST", path: "/backend/v3/api/ai/model_mappings" },
  "modelMappings.delete": { method: "DELETE", path: "/backend/v3/api/ai/model_mappings/{mappingId}" },
  "modelMappings.list": { method: "GET", path: "/backend/v3/api/ai/model_mappings" },
  "modelMappings.replace": { method: "PUT", path: "/backend/v3/api/ai/model_mappings" },
  "modelMappings.resolve.create": { method: "POST", path: "/backend/v3/api/ai/model_mappings/resolve" },
  "modelMappings.update": { method: "PATCH", path: "/backend/v3/api/ai/model_mappings/{mappingId}" },
  "modelRankings.jobs.list": { method: "GET", path: "/backend/v3/api/ai/model_rankings/jobs" },
  "modelRankings.list": { method: "GET", path: "/backend/v3/api/ai/model_rankings" },
  "modelRankings.refresh": { method: "POST", path: "/backend/v3/api/ai/model_rankings/refresh" },
  "modelRankings.status.retrieve": { method: "GET", path: "/backend/v3/api/ai/model_rankings/status" },
  "models.create": { method: "POST", path: "/backend/v3/api/ai/models" },
  "models.delete": { method: "DELETE", path: "/backend/v3/api/ai/models/{modelId}" },
  "models.list": { method: "GET", path: "/backend/v3/api/ai/models" },
  "models.refresh": { method: "POST", path: "/backend/v3/api/ai/models/refresh" },
  "models.update": { method: "PATCH", path: "/backend/v3/api/ai/models/{modelId}" },
  "modelVendors.create": { method: "POST", path: "/backend/v3/api/ai/model_vendors" },
  "modelVendors.list": { method: "GET", path: "/backend/v3/api/ai/model_vendors" },
} as const;
