/* This file is generated by tools/generate-mainstream-agent-model-catalog.mjs. */
import type { OfficialModelVendorPreset } from './agentModelAccessSelectorTypes';

export const SDKWORK_OFFICIAL_MODEL_VENDOR_PRESETS = [
  {
    "baseUrl": "https://api.birdcoder.com/v1",
    "channelName": "OpenAI",
    "protocol": "openai_compatible",
    "providerCode": "openai_direct",
    "providerDisplayName": "OpenAI direct",
    "models": [
      {
        "catalogKey": "openai/gpt-5.4-mini",
        "model": "gpt-5.4-mini",
        "displayName": "GPT-5.4 Mini",
        "sortOrder": 5
      },
      {
        "catalogKey": "openai/gpt-5.4-nano",
        "model": "gpt-5.4-nano",
        "displayName": "GPT-5.4 Nano",
        "sortOrder": 6
      },
      {
        "catalogKey": "openai/gpt-5.4-pro",
        "model": "gpt-5.4-pro",
        "displayName": "GPT-5.4 Pro",
        "sortOrder": 7
      },
      {
        "catalogKey": "openai/gpt-5.4",
        "model": "gpt-5.4",
        "displayName": "GPT-5.4",
        "sortOrder": 8
      },
      {
        "catalogKey": "openai/gpt-5.5-pro",
        "model": "gpt-5.5-pro",
        "displayName": "GPT-5.5 Pro",
        "sortOrder": 9
      },
      {
        "catalogKey": "openai/gpt-5.5",
        "model": "gpt-5.5",
        "displayName": "GPT-5.5",
        "sortOrder": 10
      },
      {
        "catalogKey": "openai/gpt-5.6-luna",
        "model": "gpt-5.6-luna",
        "displayName": "GPT-5.6 Luna",
        "sortOrder": 11
      },
      {
        "catalogKey": "openai/gpt-5.6-sol",
        "model": "gpt-5.6-sol",
        "displayName": "GPT-5.6 Sol",
        "sortOrder": 12
      },
      {
        "catalogKey": "openai/gpt-5.6-terra",
        "model": "gpt-5.6-terra",
        "displayName": "GPT-5.6 Terra",
        "sortOrder": 13
      }
    ],
    "sortOrder": 0,
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "baseUrl": "https://api.birdcoder.com",
    "channelName": "Anthropic",
    "protocol": "anthropic_messages",
    "providerCode": "anthropic_direct",
    "providerDisplayName": "Anthropic direct",
    "models": [
      {
        "catalogKey": "anthropic/claude-fable-5",
        "model": "claude-fable-5",
        "displayName": "Claude Fable 5",
        "sortOrder": 0
      },
      {
        "catalogKey": "anthropic/claude-haiku-4-5",
        "model": "claude-haiku-4-5",
        "displayName": "Claude Haiku 4.5",
        "sortOrder": 1
      },
      {
        "catalogKey": "anthropic/claude-opus-4-7",
        "model": "claude-opus-4-7",
        "displayName": "Claude Opus 4.7",
        "sortOrder": 3
      },
      {
        "catalogKey": "anthropic/claude-opus-4-8",
        "model": "claude-opus-4-8",
        "displayName": "Claude Opus 4.8",
        "sortOrder": 4
      },
      {
        "catalogKey": "anthropic/claude-opus-5",
        "model": "claude-opus-5",
        "displayName": "Claude Opus 5",
        "sortOrder": 5
      },
      {
        "catalogKey": "anthropic/claude-sonnet-4-6",
        "model": "claude-sonnet-4-6",
        "displayName": "Claude Sonnet 4.6",
        "sortOrder": 6
      },
      {
        "catalogKey": "anthropic/claude-sonnet-5",
        "model": "claude-sonnet-5",
        "displayName": "Claude Sonnet 5",
        "sortOrder": 7
      }
    ],
    "sortOrder": 1,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "baseUrl": "https://api.birdcoder.com",
    "channelName": "Google",
    "protocol": "google_gemini",
    "providerCode": "google_ai_direct",
    "providerDisplayName": "Google AI direct",
    "models": [
      {
        "catalogKey": "google/gemini-3-flash-preview",
        "model": "gemini-3-flash-preview",
        "displayName": "Gemini 3 Flash Preview",
        "sortOrder": 3
      },
      {
        "catalogKey": "google/gemini-3.1-flash-lite-preview",
        "model": "gemini-3.1-flash-lite-preview",
        "displayName": "Gemini 3.1 Flash Lite Preview",
        "sortOrder": 7
      },
      {
        "catalogKey": "google/gemini-3.1-flash-lite",
        "model": "gemini-3.1-flash-lite",
        "displayName": "Gemini 3.1 Flash Lite",
        "sortOrder": 8
      },
      {
        "catalogKey": "google/gemini-3.1-flash-live-preview",
        "model": "gemini-3.1-flash-live-preview",
        "displayName": "Gemini 3.1 Flash Live Preview",
        "sortOrder": 9
      },
      {
        "catalogKey": "google/gemini-3.1-pro-preview",
        "model": "gemini-3.1-pro-preview",
        "displayName": "Gemini 3.1 Pro Preview",
        "sortOrder": 11
      },
      {
        "catalogKey": "google/gemini-3.1-pro",
        "model": "gemini-3.1-pro",
        "displayName": "Gemini 3.1 Pro",
        "sortOrder": 12
      },
      {
        "catalogKey": "google/gemini-3.5-flash-lite",
        "model": "gemini-3.5-flash-lite",
        "displayName": "Gemini 3.5 Flash Lite",
        "sortOrder": 13
      },
      {
        "catalogKey": "google/gemini-3.5-flash",
        "model": "gemini-3.5-flash",
        "displayName": "Gemini 3.5 Flash",
        "sortOrder": 14
      },
      {
        "catalogKey": "google/gemini-3.6-flash",
        "model": "gemini-3.6-flash",
        "displayName": "Gemini 3.6 Flash",
        "sortOrder": 15
      }
    ],
    "sortOrder": 2,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "baseUrl": "",
    "channelName": "Alibaba Cloud",
    "protocol": "",
    "providerCode": "alibaba.direct",
    "providerDisplayName": "Alibaba Cloud",
    "models": [
      {
        "catalogKey": "alibaba/qwen3.7-max",
        "model": "qwen3.7-max",
        "displayName": "Qwen3.7 Max",
        "sortOrder": 0
      }
    ],
    "sortOrder": 3,
    "vendorCode": "alibaba",
    "vendorName": "Alibaba Cloud"
  },
  {
    "baseUrl": "",
    "channelName": "Baidu AI Cloud",
    "protocol": "",
    "providerCode": "baidu.direct",
    "providerDisplayName": "Baidu AI Cloud",
    "models": [
      {
        "catalogKey": "baidu/ernie-4.5-turbo-128k",
        "model": "ernie-4.5-turbo-128k",
        "displayName": "ERNIE 4.5 Turbo",
        "sortOrder": 0
      },
      {
        "catalogKey": "baidu/ernie-5.0-thinking-preview",
        "model": "ernie-5.0-thinking-preview",
        "displayName": "ERNIE 5.0 Thinking Preview",
        "sortOrder": 1
      },
      {
        "catalogKey": "baidu/ernie-5.1",
        "model": "ernie-5.1",
        "displayName": "ERNIE 5.1",
        "sortOrder": 2
      }
    ],
    "sortOrder": 5,
    "vendorCode": "baidu",
    "vendorName": "Baidu AI Cloud"
  },
  {
    "baseUrl": "",
    "channelName": "ByteDance",
    "protocol": "",
    "providerCode": "bytedance.direct",
    "providerDisplayName": "ByteDance",
    "models": [
      {
        "catalogKey": "bytedance/doubao-seed-2-0-code-preview-260215",
        "model": "doubao-seed-2-0-code-preview-260215",
        "displayName": "Doubao Seed 2.0 Code",
        "sortOrder": 0
      },
      {
        "catalogKey": "bytedance/doubao-seed-2-0-lite-260215",
        "model": "doubao-seed-2-0-lite-260215",
        "displayName": "Doubao Seed 2.0 Lite",
        "sortOrder": 1
      },
      {
        "catalogKey": "bytedance/doubao-seed-2-0-mini-260215",
        "model": "doubao-seed-2-0-mini-260215",
        "displayName": "Doubao Seed 2.0 Mini",
        "sortOrder": 2
      },
      {
        "catalogKey": "bytedance/doubao-seed-2-0-pro-260215",
        "model": "doubao-seed-2-0-pro-260215",
        "displayName": "Doubao Seed 2.0 Pro",
        "sortOrder": 3
      },
      {
        "catalogKey": "bytedance/doubao-seed-2-1-pro-260628",
        "model": "doubao-seed-2-1-pro-260628",
        "displayName": "Doubao Seed 2.1 Pro",
        "sortOrder": 4
      },
      {
        "catalogKey": "bytedance/doubao-seed-2-1-turbo-260628",
        "model": "doubao-seed-2-1-turbo-260628",
        "displayName": "Doubao Seed 2.1 Turbo",
        "sortOrder": 5
      }
    ],
    "sortOrder": 6,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "baseUrl": "",
    "channelName": "DeepSeek",
    "protocol": "",
    "providerCode": "deepseek.direct",
    "providerDisplayName": "DeepSeek",
    "models": [
      {
        "catalogKey": "deepseek/deepseek-v4-flash",
        "model": "deepseek-v4-flash",
        "displayName": "DeepSeek V4 Flash",
        "sortOrder": 0
      },
      {
        "catalogKey": "deepseek/deepseek-v4-pro",
        "model": "deepseek-v4-pro",
        "displayName": "DeepSeek V4 Pro",
        "sortOrder": 1
      }
    ],
    "sortOrder": 7,
    "vendorCode": "deepseek",
    "vendorName": "DeepSeek"
  },
  {
    "baseUrl": "",
    "channelName": "Meituan",
    "protocol": "",
    "providerCode": "meituan.direct",
    "providerDisplayName": "Meituan",
    "models": [
      {
        "catalogKey": "meituan/longcat-1.0",
        "model": "longcat-1.0",
        "displayName": "LongCat 1.0",
        "sortOrder": 0
      },
      {
        "catalogKey": "meituan/longcat-2.0",
        "model": "longcat-2.0",
        "displayName": "LongCat 2.0",
        "sortOrder": 1
      }
    ],
    "sortOrder": 9,
    "vendorCode": "meituan",
    "vendorName": "Meituan"
  },
  {
    "baseUrl": "",
    "channelName": "MiniMax",
    "protocol": "",
    "providerCode": "minimax.direct",
    "providerDisplayName": "MiniMax",
    "models": [
      {
        "catalogKey": "minimax/M2-her",
        "model": "M2-her",
        "displayName": "MiniMax M2-her",
        "sortOrder": 4
      },
      {
        "catalogKey": "minimax/MiniMax-M2.5-highspeed",
        "model": "MiniMax-M2.5-highspeed",
        "displayName": "MiniMax M2.5 Highspeed",
        "sortOrder": 6
      },
      {
        "catalogKey": "minimax/MiniMax-M2.5",
        "model": "MiniMax-M2.5",
        "displayName": "MiniMax M2.5",
        "sortOrder": 7
      },
      {
        "catalogKey": "minimax/MiniMax-M2.7-highspeed",
        "model": "MiniMax-M2.7-highspeed",
        "displayName": "MiniMax M2.7 Highspeed",
        "sortOrder": 8
      },
      {
        "catalogKey": "minimax/MiniMax-M2.7",
        "model": "MiniMax-M2.7",
        "displayName": "MiniMax M2.7",
        "sortOrder": 9
      }
    ],
    "sortOrder": 10,
    "vendorCode": "minimax",
    "vendorName": "MiniMax"
  },
  {
    "baseUrl": "",
    "channelName": "Moonshot Kimi",
    "protocol": "",
    "providerCode": "moonshot.direct",
    "providerDisplayName": "Moonshot Kimi",
    "models": [
      {
        "catalogKey": "moonshot/kimi-k2.6",
        "model": "kimi-k2.6",
        "displayName": "Kimi K2.6",
        "sortOrder": 1
      },
      {
        "catalogKey": "moonshot/kimi-k3",
        "model": "kimi-k3",
        "displayName": "Kimi K3",
        "sortOrder": 5
      }
    ],
    "sortOrder": 11,
    "vendorCode": "moonshot",
    "vendorName": "Moonshot Kimi"
  },
  {
    "baseUrl": "",
    "channelName": "StepFun",
    "protocol": "",
    "providerCode": "stepfun.direct",
    "providerDisplayName": "StepFun",
    "models": [
      {
        "catalogKey": "stepfun/step-3.5-flash-2603",
        "model": "step-3.5-flash-2603",
        "displayName": "Step 3.5 Flash 2603",
        "sortOrder": 0
      },
      {
        "catalogKey": "stepfun/step-3.5-flash",
        "model": "step-3.5-flash",
        "displayName": "Step 3.5 Flash",
        "sortOrder": 1
      },
      {
        "catalogKey": "stepfun/step-3.7-flash",
        "model": "step-3.7-flash",
        "displayName": "Step 3.7 Flash",
        "sortOrder": 2
      }
    ],
    "sortOrder": 13,
    "vendorCode": "stepfun",
    "vendorName": "StepFun"
  },
  {
    "baseUrl": "",
    "channelName": "Tencent Cloud",
    "protocol": "",
    "providerCode": "tencent.direct",
    "providerDisplayName": "Tencent Cloud",
    "models": [
      {
        "catalogKey": "tencent/hy3",
        "model": "hy3",
        "displayName": "Hy3",
        "sortOrder": 3
      }
    ],
    "sortOrder": 14,
    "vendorCode": "tencent",
    "vendorName": "Tencent Cloud"
  },
  {
    "baseUrl": "",
    "channelName": "xAI",
    "protocol": "",
    "providerCode": "xai.direct",
    "providerDisplayName": "xAI",
    "models": [
      {
        "catalogKey": "xai/grok-4.20-0309-non-reasoning",
        "model": "grok-4.20-0309-non-reasoning",
        "displayName": "Grok 4.20",
        "sortOrder": 0
      },
      {
        "catalogKey": "xai/grok-4.3",
        "model": "grok-4.3",
        "displayName": "Grok 4.3",
        "sortOrder": 3
      },
      {
        "catalogKey": "xai/grok-4.5",
        "model": "grok-4.5",
        "displayName": "Grok 4.5",
        "sortOrder": 4
      },
      {
        "catalogKey": "xai/grok-build-0.1",
        "model": "grok-build-0.1",
        "displayName": "Grok Build 0.1",
        "sortOrder": 5
      }
    ],
    "sortOrder": 15,
    "vendorCode": "xai",
    "vendorName": "xAI"
  },
  {
    "baseUrl": "",
    "channelName": "Xiaomi MiMo",
    "protocol": "",
    "providerCode": "xiaomi.direct",
    "providerDisplayName": "Xiaomi MiMo",
    "models": [
      {
        "catalogKey": "xiaomi/mimo-v2.5-pro-fp4-dflash",
        "model": "mimo-v2.5-pro-fp4-dflash",
        "displayName": "MiMo V2.5 Pro FP4 DFlash",
        "sortOrder": 1
      },
      {
        "catalogKey": "xiaomi/mimo-v2.5-pro-ultraspeed",
        "model": "mimo-v2.5-pro-ultraspeed",
        "displayName": "MiMo V2.5 Pro UltraSpeed",
        "sortOrder": 2
      },
      {
        "catalogKey": "xiaomi/mimo-v2.5-pro",
        "model": "mimo-v2.5-pro",
        "displayName": "MiMo V2.5 Pro",
        "sortOrder": 3
      },
      {
        "catalogKey": "xiaomi/mimo-v2.5",
        "model": "mimo-v2.5",
        "displayName": "MiMo V2.5",
        "sortOrder": 4
      }
    ],
    "sortOrder": 16,
    "vendorCode": "xiaomi",
    "vendorName": "Xiaomi MiMo"
  },
  {
    "baseUrl": "",
    "channelName": "Zhipu AI",
    "protocol": "",
    "providerCode": "zhipu.direct",
    "providerDisplayName": "Zhipu AI",
    "models": [
      {
        "catalogKey": "zhipu/glm-5.1",
        "model": "glm-5.1",
        "displayName": "GLM-5.1",
        "sortOrder": 3
      },
      {
        "catalogKey": "zhipu/glm-5.2",
        "model": "glm-5.2",
        "displayName": "GLM-5.2",
        "sortOrder": 4
      }
    ],
    "sortOrder": 17,
    "vendorCode": "zhipu",
    "vendorName": "Zhipu AI"
  }
] as const satisfies readonly OfficialModelVendorPreset[];
