use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

use crate::paths::SDK_DOMAIN;

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/model_vendors",
        SDK_DOMAIN,
        "modelVendors.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/model_vendors",
        SDK_DOMAIN,
        "modelVendors.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/models",
        SDK_DOMAIN,
        "models.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/models",
        SDK_DOMAIN,
        "models.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/models/refresh",
        SDK_DOMAIN,
        "models.refresh",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/ai/models/{modelId}",
        SDK_DOMAIN,
        "models.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/ai/models/{modelId}",
        SDK_DOMAIN,
        "models.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/model_mappings",
        SDK_DOMAIN,
        "modelMappings.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/model_mappings",
        SDK_DOMAIN,
        "modelMappings.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/model_mappings/resolve",
        SDK_DOMAIN,
        "modelMappings.resolve.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/ai/model_mappings/{mappingId}",
        SDK_DOMAIN,
        "modelMappings.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/ai/model_mappings/{mappingId}",
        SDK_DOMAIN,
        "modelMappings.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/model_rankings",
        SDK_DOMAIN,
        "modelRankings.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/model_rankings/status",
        SDK_DOMAIN,
        "modelRankings.status.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/model_rankings/jobs",
        SDK_DOMAIN,
        "modelRankings.jobs.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/model_rankings/refresh",
        SDK_DOMAIN,
        "modelRankings.refresh",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/resources",
        SDK_DOMAIN,
        "aiResources.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/resources",
        SDK_DOMAIN,
        "aiResources.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/backend/v3/api/ai/resources/{resourceId}",
        SDK_DOMAIN,
        "aiResources.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/resource_groups",
        SDK_DOMAIN,
        "aiResourceGroups.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/ai/resource_groups",
        SDK_DOMAIN,
        "aiResourceGroups.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/ai/resource_groups/{groupIdOrCode}/resources",
        SDK_DOMAIN,
        "aiResourceGroups.resources.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/ai/resource_groups/{groupId}",
        SDK_DOMAIN,
        "aiResourceGroups.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/ai/resource_groups/{groupId}",
        SDK_DOMAIN,
        "aiResourceGroups.delete",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
