/* This file is generated by tools/generate-mainstream-agent-model-catalog.mjs. */
import type { MainstreamAgentModelCatalogEntry } from './unifiedAgentModelCatalog';

export const SDKWORK_MODELS_CATALOG_VERSION = "2026.07.26.1";
export const SDKWORK_MODELS_CATALOG_GENERATED_AT = "2026-07-26T00:00:00Z";

export const SDKWORK_MAINSTREAM_AGENT_MODEL_CATALOG = [
  {
    "catalogKey": "openai/gpt-5.6-sol",
    "catalogVersion": "2026.07.26.1",
    "description": "GPT-5.6 Sol flagship model with max reasoning and ultra sub-agent modes. Generally available as of July 2026.",
    "displayName": "GPT-5.6 Sol",
    "lifecycle": "active",
    "modelId": "gpt-5.6-sol",
    "rankScore": 1220,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5",
      "Reasoning",
      "Coding",
      "Agents",
      "Cyber defense"
    ],
    "sortOrder": 0,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.5-pro",
    "catalogVersion": "2026.07.26.1",
    "description": "OpenAI GPT-5.5 Pro frontier model for maximum reasoning depth, coding, and agentic workloads.",
    "displayName": "GPT-5.5 Pro",
    "lifecycle": "active",
    "modelId": "gpt-5.5-pro",
    "rankScore": 1190,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5",
      "Reasoning",
      "Coding",
      "Agents",
      "Vision"
    ],
    "sortOrder": 1,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.5",
    "catalogVersion": "2026.07.26.1",
    "description": "Current OpenAI frontier model for coding, reasoning, and agentic workloads.",
    "displayName": "GPT-5.5",
    "lifecycle": "active",
    "modelId": "gpt-5.5",
    "rankScore": 1180,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5",
      "Reasoning",
      "Coding",
      "Agents",
      "Vision"
    ],
    "sortOrder": 2,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.4-pro",
    "catalogVersion": "2026.07.26.1",
    "description": "OpenAI GPT-5.4 Pro model for the highest reasoning, coding, and agent workloads on the GPT-5.4 generation.",
    "displayName": "GPT-5.4 Pro",
    "lifecycle": "active",
    "modelId": "gpt-5.4-pro",
    "rankScore": 1170,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5",
      "Reasoning",
      "Coding",
      "Agents",
      "Vision"
    ],
    "sortOrder": 3,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.4",
    "catalogVersion": "2026.07.26.1",
    "description": "OpenAI GPT-5.4 multimodal model for high-quality reasoning and generation.",
    "displayName": "GPT-5.4",
    "lifecycle": "active",
    "modelId": "gpt-5.4",
    "rankScore": 1160,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5",
      "Reasoning",
      "Coding",
      "Vision",
      "Multimodal output"
    ],
    "sortOrder": 4,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.6-terra",
    "catalogVersion": "2026.07.26.1",
    "description": "GPT-5.6 Terra balanced model for everyday work at roughly half the cost of GPT-5.5. Generally available as of July 2026.",
    "displayName": "GPT-5.6 Terra",
    "lifecycle": "active",
    "modelId": "gpt-5.6-terra",
    "rankScore": 1150,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5",
      "Reasoning",
      "Coding",
      "Cost efficient"
    ],
    "sortOrder": 5,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.6-luna",
    "catalogVersion": "2026.07.26.1",
    "description": "GPT-5.6 Luna fast and affordable tier for latency-sensitive workloads. Generally available as of July 2026.",
    "displayName": "GPT-5.6 Luna",
    "lifecycle": "active",
    "modelId": "gpt-5.6-luna",
    "rankScore": 1050,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5",
      "Fast inference",
      "Low cost",
      "Agents"
    ],
    "sortOrder": 6,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.4-mini",
    "catalogVersion": "2026.07.26.1",
    "description": "Compact GPT-5.4 model for cost-sensitive chat, coding, and agent workloads.",
    "displayName": "GPT-5.4 Mini",
    "lifecycle": "active",
    "modelId": "gpt-5.4-mini",
    "rankScore": 1030,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5",
      "Cost efficient",
      "Reasoning",
      "Vision"
    ],
    "sortOrder": 7,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.4-nano",
    "catalogVersion": "2026.07.26.1",
    "description": "Smallest GPT-5.4 model for high-throughput, low-cost routing.",
    "displayName": "GPT-5.4 Nano",
    "lifecycle": "active",
    "modelId": "gpt-5.4-nano",
    "rankScore": 910,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5",
      "Low latency",
      "Low cost",
      "Vision"
    ],
    "sortOrder": 8,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "anthropic/claude-opus-5",
    "catalogVersion": "2026.07.26.1",
    "description": "Claude Opus 5 frontier model released July 24, 2026; step-change improvement over Claude Opus 4.8 with 1M token context window, 128k max output, thinking on by default, and the full effort ladder (low/medium/high/xhigh/max).",
    "displayName": "Claude Opus 5",
    "lifecycle": "active",
    "modelId": "claude-opus-5",
    "rankScore": 1230,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Reasoning",
      "Coding",
      "Agents",
      "Long context",
      "Thinking"
    ],
    "sortOrder": 9,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-opus-4-8",
    "catalogVersion": "2026.07.26.1",
    "description": "Current Claude Opus frontier model for complex reasoning, coding, and agentic work.",
    "displayName": "Claude Opus 4.8",
    "lifecycle": "active",
    "modelId": "claude-opus-4-8",
    "rankScore": 1185,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Reasoning",
      "Coding",
      "Agents",
      "Long context"
    ],
    "sortOrder": 10,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-opus-4-7",
    "catalogVersion": "2026.07.26.1",
    "description": "Current Claude Opus frontier model for complex reasoning, coding, and agentic work.",
    "displayName": "Claude Opus 4.7",
    "lifecycle": "active",
    "modelId": "claude-opus-4-7",
    "rankScore": 1170,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Reasoning",
      "Coding",
      "Agents",
      "Long context"
    ],
    "sortOrder": 11,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-sonnet-5",
    "catalogVersion": "2026.07.26.1",
    "description": "Claude Sonnet 5 is Anthropic's most agentic Sonnet model for coding, tool use, and autonomous workflows with introductory API pricing through August 2026.",
    "displayName": "Claude Sonnet 5",
    "lifecycle": "active",
    "modelId": "claude-sonnet-5",
    "rankScore": 1120,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Agents",
      "Coding",
      "Tool use",
      "Long context"
    ],
    "sortOrder": 12,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-sonnet-4-6",
    "catalogVersion": "2026.07.26.1",
    "description": "Claude Sonnet model for reasoning, coding, and agent workflows.",
    "displayName": "Claude Sonnet 4.6",
    "lifecycle": "active",
    "modelId": "claude-sonnet-4-6",
    "rankScore": 1080,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Reasoning",
      "Coding",
      "Long context",
      "Agents"
    ],
    "sortOrder": 13,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-haiku-4-5",
    "catalogVersion": "2026.07.26.1",
    "description": "Fast Claude model for cost-sensitive chat, coding assistance, and agent sub-tasks.",
    "displayName": "Claude Haiku 4.5",
    "lifecycle": "active",
    "modelId": "claude-haiku-4-5",
    "rankScore": 980,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Low latency",
      "Cost efficient",
      "Vision",
      "Tool use"
    ],
    "sortOrder": 14,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "google/gemini-3.6-flash",
    "catalogVersion": "2026.07.26.1",
    "description": "Gemini 3.6 Flash main-tier model with 17% fewer output tokens than 3.5 Flash, improved agentic coding and multimodal efficiency.",
    "displayName": "Gemini 3.6 Flash",
    "lifecycle": "active",
    "modelId": "gemini-3.6-flash",
    "rankScore": 1060,
    "releaseStage": "active",
    "searchTerms": [
      "gemini",
      "Agents",
      "Coding",
      "Multimodal",
      "Token efficiency"
    ],
    "sortOrder": 15,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.5-flash-lite",
    "catalogVersion": "2026.07.26.1",
    "description": "Fastest, most cost-efficient Gemini 3.5 Flash Lite for high-throughput agentic search and document processing at 350 tokens/sec.",
    "displayName": "Gemini 3.5 Flash Lite",
    "lifecycle": "active",
    "modelId": "gemini-3.5-flash-lite",
    "rankScore": 980,
    "releaseStage": "active",
    "searchTerms": [
      "gemini",
      "Lowest cost",
      "Low latency",
      "Multimodal",
      "High throughput"
    ],
    "sortOrder": 16,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.1-pro",
    "catalogVersion": "2026.07.26.1",
    "description": "Gemini 3.1 Pro is Google's latest production-ready pro-tier model for complex reasoning, coding, and multimodal tasks.",
    "displayName": "Gemini 3.1 Pro",
    "lifecycle": "active",
    "modelId": "gemini-3.1-pro",
    "rankScore": 935,
    "releaseStage": "active",
    "searchTerms": [
      "gemini",
      "Reasoning",
      "Coding",
      "Multimodal",
      "Long context"
    ],
    "sortOrder": 17,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.1-pro-preview",
    "catalogVersion": "2026.07.26.1",
    "description": "Preview multimodal Gemini model for long-context reasoning.",
    "displayName": "Gemini 3.1 Pro Preview",
    "lifecycle": "preview",
    "modelId": "gemini-3.1-pro-preview",
    "rankScore": 1050,
    "releaseStage": "preview",
    "searchTerms": [
      "gemini",
      "Long context",
      "Multimodal",
      "Reasoning"
    ],
    "sortOrder": 18,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3-flash-preview",
    "catalogVersion": "2026.07.26.1",
    "description": "Fast Gemini 3 preview model for multimodal chat and cost-sensitive reasoning.",
    "displayName": "Gemini 3 Flash Preview",
    "lifecycle": "preview",
    "modelId": "gemini-3-flash-preview",
    "rankScore": 990,
    "releaseStage": "preview",
    "searchTerms": [
      "gemini",
      "Low latency",
      "Multimodal",
      "Reasoning",
      "Cost efficient"
    ],
    "sortOrder": 19,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.1-flash-lite-preview",
    "catalogVersion": "2026.07.26.1",
    "description": "Preview Gemini 3.1 Flash Lite model for low-cost multimodal chat.",
    "displayName": "Gemini 3.1 Flash Lite Preview",
    "lifecycle": "preview",
    "modelId": "gemini-3.1-flash-lite-preview",
    "rankScore": 925,
    "releaseStage": "preview",
    "searchTerms": [
      "gemini",
      "Low cost",
      "Low latency",
      "Multimodal"
    ],
    "sortOrder": 20,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.1-flash-live-preview",
    "catalogVersion": "2026.07.26.1",
    "description": "Gemini 3.1 Flash Live preview model for low-latency multimodal realtime sessions.",
    "displayName": "Gemini 3.1 Flash Live Preview",
    "lifecycle": "preview",
    "modelId": "gemini-3.1-flash-live-preview",
    "rankScore": 900,
    "releaseStage": "preview",
    "searchTerms": [
      "gemini",
      "Realtime",
      "Audio",
      "Multimodal"
    ],
    "sortOrder": 21,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "xai/grok-4.5",
    "catalogVersion": "2026.07.26.1",
    "description": "Grok 4.5 flagship model for code, agentic tool calling, and configurable reasoning with minimal hallucinations.",
    "displayName": "Grok 4.5",
    "lifecycle": "active",
    "modelId": "grok-4.5",
    "rankScore": 950,
    "releaseStage": "active",
    "searchTerms": [
      "grok",
      "Code",
      "Reasoning",
      "Agentic tool calling",
      "Vision"
    ],
    "sortOrder": 22,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [],
    "vendorCode": "xai",
    "vendorName": "xAI"
  },
  {
    "catalogKey": "xai/grok-4.20-0309-non-reasoning",
    "catalogVersion": "2026.07.26.1",
    "description": "Grok 4.20 non-reasoning model optimized for fast general-purpose chat and instruction following.",
    "displayName": "Grok 4.20",
    "lifecycle": "active",
    "modelId": "grok-4.20-0309-non-reasoning",
    "rankScore": 935,
    "releaseStage": "active",
    "searchTerms": [
      "grok",
      "Chat",
      "Speed",
      "Vision"
    ],
    "sortOrder": 23,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [],
    "vendorCode": "xai",
    "vendorName": "xAI"
  },
  {
    "catalogKey": "xai/grok-4.3",
    "catalogVersion": "2026.07.26.1",
    "description": "Grok model for general chat, reasoning, and multimodal assistance.",
    "displayName": "Grok 4.3",
    "lifecycle": "active",
    "modelId": "grok-4.3",
    "rankScore": 930,
    "releaseStage": "active",
    "searchTerms": [
      "grok",
      "Reasoning",
      "Realtime knowledge",
      "Vision"
    ],
    "sortOrder": 24,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [],
    "vendorCode": "xai",
    "vendorName": "xAI"
  },
  {
    "catalogKey": "xai/grok-build-0.1",
    "catalogVersion": "2026.07.26.1",
    "description": "Grok Build lightweight model for fast, cost-efficient inference on simpler tasks.",
    "displayName": "Grok Build 0.1",
    "lifecycle": "active",
    "modelId": "grok-build-0.1",
    "rankScore": 800,
    "releaseStage": "active",
    "searchTerms": [
      "grok",
      "Speed",
      "Cost efficiency"
    ],
    "sortOrder": 25,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [],
    "vendorCode": "xai",
    "vendorName": "xAI"
  },
  {
    "catalogKey": "alibaba/qwen3.7-max",
    "catalogVersion": "2026.07.26.1",
    "description": "Qwen3.7-Max international flagship reasoning and agent model with 1M context.",
    "displayName": "Qwen3.7 Max",
    "lifecycle": "active",
    "modelId": "qwen3.7-max",
    "rankScore": 1060,
    "releaseStage": "active",
    "searchTerms": [
      "qwen",
      "Agents",
      "Coding",
      "Long context",
      "Tool use"
    ],
    "sortOrder": 26,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "vendorCode": "alibaba",
    "vendorName": "Alibaba Cloud"
  },
  {
    "catalogKey": "alibaba/qwen3.8-max-preview",
    "catalogVersion": "2026.07.26.1",
    "description": "Qwen3.8-Max preview flagship unveiled at WAIC 2026 on July 19, 2026; 2.4T-parameter MoE with 350B activated, native multimodal (text/image/video/document) and 1M context. Apache 2.0 weights planned.",
    "displayName": "Qwen3.8 Max Preview",
    "lifecycle": "preview",
    "modelId": "qwen3.8-max-preview",
    "rankScore": 1090,
    "releaseStage": "preview",
    "searchTerms": [
      "qwen",
      "Native multimodal",
      "Long context",
      "Agents",
      "Coding",
      "Chinese"
    ],
    "sortOrder": 27,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "vendorCode": "alibaba",
    "vendorName": "Alibaba Cloud"
  },
  {
    "catalogKey": "deepseek/deepseek-v4-pro",
    "catalogVersion": "2026.07.26.1",
    "description": "DeepSeek reasoning and coding model.",
    "displayName": "DeepSeek V4 Pro",
    "lifecycle": "active",
    "modelId": "deepseek-v4-pro",
    "rankScore": 900,
    "releaseStage": "active",
    "searchTerms": [
      "deepseek",
      "Reasoning",
      "Coding",
      "Cost efficient"
    ],
    "sortOrder": 28,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "vendorCode": "deepseek",
    "vendorName": "DeepSeek"
  },
  {
    "catalogKey": "deepseek/deepseek-v4-flash",
    "catalogVersion": "2026.07.26.1",
    "description": "Fast DeepSeek V4 model for cost-sensitive reasoning and coding traffic.",
    "displayName": "DeepSeek V4 Flash",
    "lifecycle": "active",
    "modelId": "deepseek-v4-flash",
    "rankScore": 860,
    "releaseStage": "active",
    "searchTerms": [
      "deepseek",
      "Low latency",
      "Cost efficient",
      "Coding"
    ],
    "sortOrder": 29,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "vendorCode": "deepseek",
    "vendorName": "DeepSeek"
  },
  {
    "catalogKey": "moonshot/kimi-k3",
    "catalogVersion": "2026.07.26.1",
    "description": "Kimi K3 flagship released on July 16, 2026 at WAIC 2026; 2.8T-parameter Stable LatentMoE with 16-of-896 expert activation, native multimodal vision, and 1M context for long-horizon agent coding.",
    "displayName": "Kimi K3",
    "lifecycle": "active",
    "modelId": "kimi-k3",
    "rankScore": 1090,
    "releaseStage": "active",
    "searchTerms": [
      "kimi",
      "Native multimodal",
      "Long context",
      "Agent coding",
      "Reasoning",
      "Chinese"
    ],
    "sortOrder": 30,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [],
    "vendorCode": "moonshot",
    "vendorName": "Moonshot Kimi"
  },
  {
    "catalogKey": "moonshot/kimi-k2.6",
    "catalogVersion": "2026.07.26.1",
    "description": "Kimi K2.6 model for long-context Chinese, multilingual, and agent workloads.",
    "displayName": "Kimi K2.6",
    "lifecycle": "active",
    "modelId": "kimi-k2.6",
    "rankScore": 875,
    "releaseStage": "active",
    "searchTerms": [
      "kimi",
      "Long context",
      "Chinese",
      "Reasoning",
      "Coding"
    ],
    "sortOrder": 31,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [],
    "vendorCode": "moonshot",
    "vendorName": "Moonshot Kimi"
  },
  {
    "catalogKey": "zhipu/glm-5.2",
    "catalogVersion": "2026.07.26.1",
    "description": "GLM-5.2 flagship coding and agent model with 1M context and open-weight lineage.",
    "displayName": "GLM-5.2",
    "lifecycle": "active",
    "modelId": "glm-5.2",
    "rankScore": 920,
    "releaseStage": "active",
    "searchTerms": [
      "glm",
      "Coding",
      "Agents",
      "Long context",
      "Reasoning"
    ],
    "sortOrder": 32,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [],
    "vendorCode": "zhipu",
    "vendorName": "Zhipu AI"
  },
  {
    "catalogKey": "zhipu/glm-5.1",
    "catalogVersion": "2026.07.26.1",
    "description": "GLM model for Chinese and multimodal assistance.",
    "displayName": "GLM-5.1",
    "lifecycle": "active",
    "modelId": "glm-5.1",
    "rankScore": 840,
    "releaseStage": "active",
    "searchTerms": [
      "glm",
      "Chinese",
      "Reasoning",
      "Vision"
    ],
    "sortOrder": 33,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [],
    "vendorCode": "zhipu",
    "vendorName": "Zhipu AI"
  },
  {
    "catalogKey": "xiaomi/mimo-v2.5-pro-ultraspeed",
    "catalogVersion": "2026.07.26.1",
    "description": "Xiaomi MiMo V2.5 Pro UltraSpeed - Ultra-speed inference mode of the 1T parameter MiMo-V2.5-Pro, delivering ~10x output speed (1000 TPS) through model-system codesign.",
    "displayName": "MiMo V2.5 Pro UltraSpeed",
    "lifecycle": "active",
    "modelId": "mimo-v2.5-pro-ultraspeed",
    "rankScore": 1110,
    "releaseStage": "active",
    "searchTerms": [
      "mimo-v2.5",
      "Speed",
      "Reasoning",
      "Coding",
      "Agents"
    ],
    "sortOrder": 34,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "vendorCode": "xiaomi",
    "vendorName": "Xiaomi MiMo"
  },
  {
    "catalogKey": "xiaomi/mimo-v2.5-pro",
    "catalogVersion": "2026.07.26.1",
    "description": "Xiaomi MiMo V2.5 Pro - 1T parameter MoE model with 42B active parameters, optimized for agentic and long-horizon tasks.",
    "displayName": "MiMo V2.5 Pro",
    "lifecycle": "active",
    "modelId": "mimo-v2.5-pro",
    "rankScore": 1100,
    "releaseStage": "active",
    "searchTerms": [
      "mimo-v2.5",
      "Reasoning",
      "Coding",
      "Agents",
      "Long Context"
    ],
    "sortOrder": 35,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "vendorCode": "xiaomi",
    "vendorName": "Xiaomi MiMo"
  },
  {
    "catalogKey": "xiaomi/mimo-v2.5-pro-fp4-dflash",
    "catalogVersion": "2026.07.26.1",
    "description": "Xiaomi MiMo V2.5 Pro FP4 DFlash - 554B parameter MoE model with FP4 quantization, optimized for high-speed inference.",
    "displayName": "MiMo V2.5 Pro FP4 DFlash",
    "lifecycle": "active",
    "modelId": "mimo-v2.5-pro-fp4-dflash",
    "rankScore": 1095,
    "releaseStage": "active",
    "searchTerms": [
      "mimo-v2.5",
      "Speed",
      "Reasoning",
      "Coding",
      "Agents"
    ],
    "sortOrder": 36,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "vendorCode": "xiaomi",
    "vendorName": "Xiaomi MiMo"
  },
  {
    "catalogKey": "xiaomi/mimo-v2.5",
    "catalogVersion": "2026.07.26.1",
    "description": "Xiaomi MiMo V2.5 - Native omnimodal model supporting text, image, video, and audio understanding with 310B total / 15B active parameters.",
    "displayName": "MiMo V2.5",
    "lifecycle": "active",
    "modelId": "mimo-v2.5",
    "rankScore": 1050,
    "releaseStage": "active",
    "searchTerms": [
      "mimo-v2.5",
      "Multimodal",
      "Reasoning",
      "Coding",
      "Agents",
      "Long Context"
    ],
    "sortOrder": 37,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "vendorCode": "xiaomi",
    "vendorName": "Xiaomi MiMo"
  },
  {
    "catalogKey": "xiaomi/mimo-v2-flash",
    "catalogVersion": "2026.07.26.1",
    "description": "Xiaomi MiMo V2 Flash - High-performance MoE model with 309B total / 15B active parameters, optimized for speed and cost efficiency.",
    "displayName": "MiMo V2 Flash",
    "lifecycle": "active",
    "modelId": "mimo-v2-flash",
    "rankScore": 980,
    "releaseStage": "active",
    "searchTerms": [
      "mimo-v2",
      "Speed",
      "Cost Efficiency",
      "Reasoning",
      "Coding"
    ],
    "sortOrder": 38,
    "sourceObservedAt": "2026-07-26T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "vendorCode": "xiaomi",
    "vendorName": "Xiaomi MiMo"
  }
] as const satisfies readonly MainstreamAgentModelCatalogEntry[];
