#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate a report of catalog prices that the runtime cannot select.

These entries are structurally valid (schema + migrator stable) but their
discriminator dimension is not populated by the runtime, so the rate is
unreachable: the meter resolves no price and the request fails (or falls back
across regions). Each row carries a suggested remediation; none is applied
automatically because collapsing/merging prices is a product decision.
"""
import json, glob, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS = os.path.join(ROOT, "models")

RUNTIME_DIMS = {
    "api_code", "operation_id", "tier_code", "quality", "resolution",
    "duration_seconds", "result_count", "media_type", "input_type", "output_type",
    "context_tokens", "vendor_code", "provider_code", "region_code", "catalog_key",
    "model", "meter_code", "product_code", "operation_code", "occurred_at",
}

def dim_label(dim):
    return {
        "tier_code": "request body tier (/tier_code,/service_tier,/tier) - chat never sends it",
        "media_direction": "not populated by the runtime at all",
    }.get(dim, f"not populated by the runtime ({dim})")

rows = []
for path in sorted(glob.glob(os.path.join(MODELS, "*", "*", "pricing", "*.json"))):
    try:
        pricing = json.load(open(path, encoding="utf-8"))
    except Exception:
        continue
    for p in pricing.get("prices", []):
        for c in p.get("conditions", []):
            dim = c.get("dimensionCode")
            if dim == "tier_code" and p.get("rateVariant") != "time_window":
                pass  # dead tier_code on a standard rate -> report
            elif dim in RUNTIME_DIMS:
                continue
            tier = next((cc.get("value") for cc in p.get("conditions", [])
                         if cc.get("dimensionCode") == "tier_code"), None)
            rows.append({
                "file": os.path.relpath(path, MODELS).replace(os.sep, "/"),
                "priceId": p.get("priceId"),
                "meter": p.get("meterCode"),
                "unitPrice": p.get("unitPrice"),
                "currency": p.get("currency") or pricing.get("currency"),
                "unitSize": p.get("unitSize"),
                "dimension": dim,
                "dimensionNote": dim_label(dim),
                "tierValue": tier,
                "thresholdTokens": p.get("thresholdTokens"),
            })

rows.sort(key=lambda r: (r["file"], r["priceId"]))
out = ["# Unreachable catalog prices (runtime dimension gaps)\n",
       "Generated by tools/audit-pricing-consistency.py. Structurally valid rates",
       "whose discriminator dimension the runtime never populates -> the meter",
       "resolves no price at runtime. Fixing requires either a runtime dimension",
       "or merging tiers - a product decision, so nothing here is auto-applied.\n",
       "| file | priceId | meter | price | currency | unitSize | dimension | tier | thresholdTokens |",
       "|---|---|---|---|---|---|---|---|---|"]
for r in rows:
    out.append(f"| {r['file']} | {r['priceId']} | {r['meter']} | {r['unitPrice']} | "
               f"{r['currency']} | {r['unitSize']} | {r['dimension']} | {r['tierValue'] or '-'} | "
               f"{r['thresholdTokens'] or '-'} |")

with open(os.path.join(ROOT, "docs", "pricing-unreachable-rates.md"), "w", encoding="utf-8") as fh:
    fh.write("\n".join(out) + "\n")
print(f"wrote docs/pricing-unreachable-rates.md with {len(rows)} rows")
