// Generated by tools/models_sdk_generator_runner.mjs from the owner-only Models OpenAPI input.
// This file is outside generated/server-openapi so SDK ownership metadata does not pollute sdkgen output.

export const sdkMetadata = {
  name: "sdkwork-models-app-sdk",
  packageName: "sdkwork-models-app-sdk-generated-typescript",
  sdkOwner: "sdkwork-models",
  apiAuthority: "sdkwork-models-app-api",
  language: "typescript",
  standardProfile: "sdkwork-v3",
  baseUrl: "http://127.0.0.1:18080",
  apiPrefix: "/app/v3/api",
  sdkDependencies: [{"workspace":"sdkwork-appbase-app-sdk","role":"appbase-app-capability","required":true,"dependencyMode":"consumer-sdk","apiPrefix":"/app/v3/api","apiAuthority":"sdkwork-appbase-app-api","generatedTransportImportPolicy":"forbidden","packageByLanguage":{"typescript":"@sdkwork/appbase-app-sdk","rust":"sdkwork-appbase-app-sdk","java":"com.sdkwork:sdkwork-appbase-app-sdk","python":"sdkwork-appbase-app-sdk","go":"github.com/sdkwork/sdkwork-appbase-app-sdk"}}],
  dependencyApiExports: [],
};

export const operations = {
  "modelRankings.list": { method: "GET", path: "/app/v3/api/ai/model_rankings" },
  "models.list": { method: "GET", path: "/app/v3/api/ai/models" },
  "modelVendors.list": { method: "GET", path: "/app/v3/api/ai/model_vendors" },
} as const;
